/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import controlador.ProfesorControlador;
import java.awt.CardLayout;

/**
 *
 * @author juan
 */
public class PruebaC extends javax.swing.JPanel {

     private principal Frm;
    /**
     * Creates new form PruebaC
     */
    private PruebaC pnl;
    
    public PruebaC() {
        initComponents();
        unicarespuesta1.setpnl(this);
        abierta1.setpnl(this);
        tipoPregunta1.setpnl(this);
       
        
    }
    
      public void setpnl(PruebaC pnl){
        this.pnl=pnl;
    }
    
    
    public void cambiar_tarjeta(String tarjeta){
          if(tarjeta.equals("abierta1")){
          abierta1.limpiarCampos();
        }
        else if(tarjeta.equals("Unica"))
            unicarespuesta1.limpiarCampos();
        
        ((CardLayout) jPanel2.getLayout()).show(jPanel2,tarjeta);
    }
    
    
      public principal getFrm() {
        return Frm;
    }

    public void setFrm(principal Frm) {
        this.Frm = Frm;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        terminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tipoPregunta1 = new ventanas.tipoPregunta();
        unicarespuesta1 = new ventanas.Unicarespuesta();
        abierta1 = new ventanas.Abierta();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        terminar.setText("Terminar Prueba");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(terminar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(terminar))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(tipoPregunta1, "tipo");
        jPanel2.add(unicarespuesta1, "Unica");
        jPanel2.add(abierta1, "abierta1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        // TODO add your handling code here:
        
        String Descripcion;
        Descripcion = descripcion.getText();
        Frm.cambiar_tarjeta("principal");
        ProfesorControlador.getInstance().agregarDescripcion(Descripcion);
        ProfesorControlador.getInstance().guardarPruebaArchivo();
    }//GEN-LAST:event_terminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ventanas.Abierta abierta1;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton terminar;
    private ventanas.tipoPregunta tipoPregunta1;
    private ventanas.Unicarespuesta unicarespuesta1;
    // End of variables declaration//GEN-END:variables
}
